### ISSUE TITLE
Extension for Safari browser.

### ISSUE THREAD

**Issue by Abhinav-Bhardwaj-09** [wakatime/wakatime-cli#1006]
**Extension for safari browser to track time spend on browsing.** It'll be **more beneficial** if the dashboard checks the **browsing time coming from different browsers** ( like _Safari, Chrome, Firefox and Edge_ ) but with the **same API** then add them all and show under a _single category_ as "**Browsing Time**".

**Comment by alanhamlett** [comment]
Added to the poll in https://github.com/wakatime/wakatime-cli/issues/942.
