### ISSUE TITLE
Customizable Data Exclusion in WakaTime Tracking

### ISSUE THREAD

**Issue by FaroukOyekunle** [wakatime/wakatime-cli#1033]
Is it possible to customize the data captured by WakaTime to exclude specific projects or directories? This feature would be useful for focusing on specific aspects of my coding activity.

**Comment by alanhamlett** [comment]
Yes, this feature exists:

https://wakatime.com/faq#exclude-folders

**Comment by FaroukOyekunle** [comment]
Thanks for the response.
