### ISSUE TITLE
Notion

### ISSUE THREAD

**Issue by gdpouya** [wakatime/wakatime-cli#1034]
please add notion plugin or something we can use on notion or use notion data on wakatime

**Comment by alanhamlett** [comment]
Duplicate of https://github.com/wakatime/macos-wakatime/issues/205

Or do you mean for other operating systems besides Mac? Notion doesn't support plugins like WakaTime so we need a native desktop app to track it.

**Comment by gdpouya** [comment]
but on wakatime mac i dont see notion togle button to enable it tacking

**Comment by alanhamlett** [comment]
Yes, that issue is still open. We'll update https://github.com/wakatime/macos-wakatime/issues/205 when Notion is supported.
