### ISSUE TITLE
Wakatime Doesnt work on github codespaces, config file missing

### ISSUE THREAD

**Issue by Ishannaik** [wakatime/wakatime-cli#1035]
**Environment**:

- OS:  Codespaces (linux?)
- Platform: 

![image](https://github.com/wakatime/wakatime-cli/assets/11766476/fd4e775c-b527-4d59-8264-e4bd0a50cee1)
there is no config file present for spaces and popup repeatedly comes up to enter api key
![image](https://github.com/wakatime/wakatime-cli/assets/11766476/e44cbc9b-858d-41b4-88b1-38f82deb1f8e)

**Comment by alanhamlett** [comment]
Codespaces runs in a cloud server environment. Did you open a terminal and check for the config file at `/home/codespaces/.wakatime.cfg`? I just tested and it's working for me in github codespaces.

**Comment by Ishannaik** [comment]
> Codespaces runs in a cloud server environment. Did you open a terminal and check for the config file at `/home/codespaces/.wakatime.cfg`? I just tested and it's working for me in github codespaces.

Yup a config file exists there and after opening it, it does indeed have the api key I pasted when I opened it on VSCode, I have also noticed Every time I start the Codespace or vscode I am asked for the API key again 
![image](https://github.com/wakatime/wakatime-cli/assets/11766476/39c4b9e8-b628-4859-b767-b84b7573b966)

**Comment by alanhamlett** [comment]
What's the contents of `/home/codespaces/.wakatime/wakatime.log`

**Comment by Ishannaik** [comment]
Launching codespaces always gives me this popup 
![image](https://github.com/wakatime/wakatime-cli/assets/11766476/785f2075-8277-4dde-b263-7573b90b5a12)
Getting the error
![image](https://github.com/wakatime/wakatime-cli/assets/11766476/b6634bdc-00db-4650-bd54-c86e2d7230c3)

API Key not found. `/home/codespaces/.wakatime/wakatime.log`
![image](https://github.com/wakatime/wakatime-cli/assets/11766476/b2a8dd3a-47e9-491d-a754-55e7ecab0458)

I have double checked grabbing the Secret API Key: from https://wakatime.com/settings/account

.wakatime.cfg
![image](https://github.com/wakatime/wakatime-cli/assets/11766476/a3ed6e9a-2081-4d09-a570-c647faf75fe2)

**Comment by alanhamlett** [comment]
Please add this line at the end of your `.wakatime.cfg` file:
`debug = true`

Then after a while check your `/home/codespaces/.wakatime/wakatime.log` file to see if it's looking in the wrong location for the api key, or if there's another reason it couldn't read the api key.

**Comment by Ishannaik** [comment]
```{"caller":"cmd/run.go:58","func":"cmd.Run","level":"error","message":"failed to parse config files: failed to load configuration file: error parsing config file: While parsing config: key-value delimiter not found: .w>
{"caller":"cmd/offline/offline.go:63","func":"offline.loadParams","level":"warning","message":"failed to load API parameters: api key not found or empty","now":"2024-03-20T05:03:06Z","os/arch":"linux/amd64","version":>
{"caller":"cmd/run.go:58","func":"cmd.Run","level":"error","message":"failed to parse config files: failed to load configuration file: error parsing config file: While parsing config: key-value delimiter not found: .w>
{"caller":"cmd/offline/offline.go:63","func":"offline.loadParams","level":"warning","message":"failed to load API parameters: api key not found or empty","now":"2024-03-20T05:03:07Z","os/arch":"linux/amd64","version":>
{"caller":"cmd/run.go:58","func":"cmd.Run","level":"error","message":"failed to parse config files: failed to load configuration file: error parsing config file: While parsing config: key-value delimiter not found: .w>
{"caller":"cmd/run.go:58","func":"cmd.Run","level":"error","message":"failed to parse config files: failed to load configuration file: error parsing config file: While parsing config: key-value delimiter not found: .w>
{"caller":"cmd/run.go:58","func":"cmd.Run","level":"error","message":"failed to parse config files: failed to load configuration file: error parsing config file: While parsing config: key-value delimiter not found: .w>
{"caller":"cmd/offline/offline.go:63","func":"offline.loadParams","level":"warning","message":"failed to load API parameters: api key not found or empty","now":"2024-03-21T02:34:49Z","os/arch":"linux/amd64","version":>
```
this is being spammed in the logs after adding debug = true

**Comment by alanhamlett** [comment]
Looks like your `/home/codespaces/.wakatime.cfg` file is corrupted somehow? At least that's what this error means:

```
error parsing config file: While parsing config: key-value delimiter not found
```

Try deleting your `/home/codespaces/.wakatime.cfg` file then reload the window and re-enter the api key.

**Comment by Ishannaik** [comment]
Still having the same issue, I've tried different repos as well as creating new codespaces too
The plugin works perfectly fine in Native VSCode, I'm just having issues with the codespace, I've tried opening the codespace in the browser aswell as the open in VSCode option, both are giving me the error somehow

**Comment by alanhamlett** [comment]
I'm not able to reproduce this on a GitHub codespace opened in the browser. When the codespace first launches and VSCode in the browser opens, I'm prompted to enter my WakaTime API Key. After entering the key, it saves the key correctly to `/home/codespaces/.wakatime.cfg` and never asks for it again. I verified stopping the codespace then restarting and reopening it also doesn't prompt and correctly uses the saved key from the config file.
<img width="1145" alt="Screenshot 2024-03-23 at 8 53 59 AM" src="https://github.com/wakatime/wakatime-cli/assets/522344/b2b9e18c-7df2-48de-88b7-d20f0ef3b2dc">

**Comment by alanhamlett** [comment]
We have too many issues open for this. Let's continue debugging in https://github.com/wakatime/vscode-wakatime/issues/362.
