### ISSUE TITLE
Limit the size of `wakatime.log` file

### ISSUE THREAD

**Issue by YouKnow-sys** [wakatime/wakatime-cli#1063]
seems like this file can get as big as it want, for example if you have Wakatime installed for some time if go to `%USERPROFILE%\.wakatime` in windows you can see a log file named `wakatime.log`, the thing is seems like this file don't have any limit on how big it can get... I mean the biggest that it got in my system is more then 400MB, its just too much for a log file...
I recommend putting some kind of cap on the log file size or maybe even do some kind of **rotating**...

**Comment by gandarez** [comment]
@alanhamlett wdyt? Should we keep only x lines or x size?

**Comment by alanhamlett** [comment]
Yea we should limit it's size. My `wakatime.log` file is `2.2M` right now. @YouKnow-sys curious if you have debug mode enabled? That would cause the log to grow faster than normal.

What's a good size to cap it at? How about 100M? After that we rotate the log to `wakatime.log.N` and delete log files with `N > 4`.

**Comment by YouKnow-sys** [comment]
> Yea we should limit it's size. My `wakatime.log` file is `2.2M` right now. @YouKnow-sys curious if you have debug mode enabled? That would cause the log to grow faster than normal.
> 
> What's a good size to cap it at? How about 100M? After that we rotate the log to `wakatime.log.N` and delete log files with `N > 4`.

I didn't change any settings related to my wakatime installation, is it on debug by default?
And I think 50MB for each log file would be better (still big but more manageable)
The reason that I recommend 50MB is, it's easier to share if needed, uploading 100MB just to share the log isn't very convenient.

**Comment by alanhamlett** [comment]
> I didn't change any settings related to my wakatime installation, is it on debug by default?

No, it's off by default.

**Comment by alanhamlett** [comment]
50MB sounds good to me

**Comment by gandarez** [comment]
Started working on that

**Comment by YouKnow-sys** [comment]
> > I didn't change any settings related to my wakatime installation, is it on debug by default?
> 
> No, it's off by default.

then no, Im not on debug mode
