### ISSUE TITLE
This user has no coding activity

### ISSUE THREAD

**Issue by ghost** [wakatime/wakatime-cli#1084]
![Screenshot 2024-07-29 170000](https://github.com/user-attachments/assets/295299a3-04c7-4122-aa80-c497a9afe9e7)

Hello . All options on the profile page are active, but I still get the following message on my page address https://wakatime.com/@kabiritdeveloper:
`This user has no coding activity, or has privacy settings that prevent showing it.`

![Screenshot 2024-07-29 170413](https://github.com/user-attachments/assets/bf6ca84e-aeba-40a8-9246-48af8f80c603)

**Comment by alanhamlett** [comment]
You joined today, profiles only show data from before Today:

https://wakatime.com/@kabiritdeveloper

https://wakatime.com/faq#leaderboard-vs-dashboard
