### ISSUE TITLE
why command line filename is not wakatime-cli 

### ISSUE THREAD

**Issue by bestgopher** [wakatime/wakatime-cli#1087]
I download the command line file from release page, then unzip it.  Why the filename is not wakatime-cli?

**Comment by gandarez** [comment]
It supposed to be downloaded automatically by the editor and not manually. You might rename it if you want.

**Comment by alanhamlett** [comment]
The IDE plugins download the zip file, rename the platform-specific binary to `wakatime-cli` and place it at:

`$HOME/.wakatime/wakatime-cli`

If you manually download it, you have to also manually rename the file.
