### ISSUE TITLE
Adjustable Idle Time Detection

### ISSUE THREAD

**Issue by badrshs** [wakatime/wakatime-cli#1088]
**Description:** I would like to request a feature enhancement for the WakaTime plugin that allows users to configure the idle time detection settings. Currently, WakaTime stops tracking activity after a period of inactivity, but there is no option to adjust the duration before it considers the user idle.

**Use Case:** I frequently switch between PhpStorm and a web browser for tasks such as research or making updates. During these brief periods away from PhpStorm, I would like the ability to keep the coding time tracked for a specific duration before it is marked as idle. This would help ensure that my time tracking remains accurate even when I'm working across multiple applications.

**Proposed Solution:**

- Add a setting in the WakaTime plugin configuration where users can specify an "idle timeout" period (e.g., 10 minutes).
- If the user is inactive in PhpStorm for less than the specified timeout period, WakaTime should continue to track time as if the user is active.
- Include options to set the timeout period or disable it if preferred.

**Benefits:**
- More accurate tracking of coding time when users switch between applications for short periods.
- Improved productivity insights for users who work in multi-application environments.

If there are existing workarounds or settings that might help achieve similar results, kindly let me know.

**Comment by alanhamlett** [comment]
That's what the [keystroke timeout](https://wakatime.com/faq#timeout) setting is for.
