### ISSUE TITLE
Behavior when `hide_project_names` and `exclude` are both true

### ISSUE THREAD

**Issue by ArtofBugs** [wakatime/wakatime-cli#1129]
In my `.wakatime.cfg` right now, I have both `exclude = true` to exclude all projects (along with a list of specific folders to include under the `include` key) and `hide_project_names = true`. I would expect that any folders not in the `include` list would be ignored, but right now anytime I open any folder in vscode and edit a file, a `.wakatime-project` file is created and times for the project appear on my dashboard. Is this intended behavior? I didn't see anything about this behavior in the docs.

**Comment by gandarez** [comment]
@ArtofBugs `exclude` accepts a list of regular expressions and does not accept "true" as global variable to ignore everything.

https://github.com/wakatime/wakatime-cli/blob/develop/USAGE.md#settings-section

**Comment by ArtofBugs** [comment]
Ohh ok, that would explain things. I saw that bools were accepted in the example config table (the one you linked) so I assumed `true` worked too. Thanks!

**Comment by ArtofBugs** [comment]
Confirmed it works correctly with regex instead of `true`; closing :) Thanks for the quick reply!

**Comment by alanhamlett** [comment]
We should treat `true` as `.*` same as other bool/list configs?

**Comment by gandarez** [comment]
Implemented by https://github.com/wakatime/wakatime-cli/pull/1130 and will be released soon.

**Comment by gandarez** [comment]
Released on [v1.105.2](https://github.com/wakatime/wakatime-cli/releases/tag/v1.105.2)
