### ISSUE TITLE
Statistics not displayed

### ISSUE THREAD

**Issue by sam-amirpoor** [wakatime/wakatime-cli#1140]
Hello
I am on Windows platform and I have a wakatime account and I have connected the API key to vsCode but my coding statistics are not showing in the wakatime dashboard for a while
Please follow up

**Comment by alanhamlett** [comment]
Please follow the instructions at:

https://wakatime.com/faq#debug-plugins

and 

https://wakatime.com/faq#finding-error-messages-in-logfiles
