### ISSUE TITLE
Supported IDEs migration

### ISSUE THREAD

**Issue by gandarez** [wakatime/wakatime-cli#136]
This issue aims to map all supported IDEs and their engines to download the current wakatime python cli.

* [x] ~~Android Studio - Downloads a zipped file from S3. [ref here](https://github.com/wakatime/jetbrains-wakatime/blob/786ab90f99bb8161791446da6ea95a5bf87fdc64/src/com/wakatime/intellij/plugin/Dependencies.java#L131).~~ now using new Go wakatime-cli
* [x] ~~AppCode - Downloads a zipped file from S3. [ref here](https://github.com/wakatime/jetbrains-wakatime/blob/786ab90f99bb8161791446da6ea95a5bf87fdc64/src/com/wakatime/intellij/plugin/Dependencies.java#L131).~~ now using new Go wakatime-cli
* [x] ~~Aptana - Downloads a zipped file from wakatime repo. [ref here](https://github.com/wakatime/eclipse-wakatime/blob/master/com.wakatime.eclipse.plugin/src/com/wakatime/eclipse/plugin/Dependencies.java#L160).~~ now using new Go wakatime-cli
* [x] ~~Atom - Downloads a zipped file from S3. [ref here](https://github.com/wakatime/atom-wakatime/blob/master/lib/wakatime.coffee#L313).~~ now using new Go wakatime-cli
* [x] ~~Azure Data Studio - Downloads either from wakatime repo or S3 deppending on standalone flag. [ref here](https://github.com/wakatime/vscode-wakatime/blob/master/src/dependencies.ts#L29).~~ now using new Go wakatime-cli
* [x] ~~Blender - Uses legacy Python cli via downloading GitHub master zip. [ref here](https://github.com/allista/WakatimeBlender/blob/master/WakaTime.py#L226).~~ now using Go wakatime-cli
* [ ] Brackets - **Dos not download cli, sends heartbeats directly to API**. [ref here](https://github.com/wakatime/brackets-wakatime/blob/master/main.js).
* [x] Google Chrome - **Does not use cli, sends data directly to API**. [ref here](https://github.com/wakatime/chrome-wakatime).
* [x] ~~CLion - Downloads a zipped file from S3. [ref here](https://github.com/wakatime/jetbrains-wakatime/blob/786ab90f99bb8161791446da6ea95a5bf87fdc64/src/com/wakatime/intellij/plugin/Dependencies.java#L131).~~ now using new Go wakatime-cli
* [x] Cloud9 - **Do not download cli**. [ref here](https://github.com/wakatime/c9-wakatime).
* [ ] Coda - It embeds wakatime into `Resource` folder. [ref here](https://github.com/wakatime/coda-wakatime/blob/master/WakaTime.m#L49).
* [x] CodeTasty - **Do not download cli**. [ref here](https://github.com/codetasty/ext.wakatime/blob/master/extension.js).
* [x] ~~DataGrip - Downloads a zipped file from S3. [ref here](https://github.com/wakatime/jetbrains-wakatime/blob/786ab90f99bb8161791446da6ea95a5bf87fdc64/src/com/wakatime/intellij/plugin/Dependencies.java#L131).~~ now using new Go wakatime-cli
* [x] ~~Eclipse - Downloads a zipped file from wakatime repo. [ref here](https://github.com/wakatime/eclipse-wakatime/blob/master/com.wakatime.eclipse.plugin/src/com/wakatime/eclipse/plugin/Dependencies.java#L160).~~ now using new Go wakatime-cli
* [x] ~~Emacs - **Do not download cli**. [ref here](https://github.com/wakatime/wakatime-mode/blob/master/wakatime-mode.el).~~ now using new Go wakatime-cli via updated install instructions
* [ ] Eric6 - Downloads legacy python cli from GitHub. [ref here](https://github.com/wakatime/eric6-wakatime/blob/master/PluginWakaTime.py#L380).
* [x] ~~Excel - Downloads a zipped file from S3. [ref here](https://github.com/wakatime/nuget-wakatime-shared-extension-utils/blob/master/src/WakaTime.Shared.ExtensionUtils/Dependencies.cs#L50).~~ now using new Go wakatime-cli
* [x] ~~Flash Builder - Downloads a zipped file from wakatime repo. [ref here](https://github.com/wakatime/eclipse-wakatime/blob/master/com.wakatime.eclipse.plugin/src/com/wakatime/eclipse/plugin/Dependencies.java#L160).~~ now using new Go wakatime-cli
* [x] ~~Gedit - **Do not download cli**. [ref here](https://github.com/wakatime/gedit-wakatime).~~ now using new Go wakatime-cli
* [x] ~~GoLand - Downloads a zipped file from S3. [ref here](https://github.com/wakatime/jetbrains-wakatime/blob/786ab90f99bb8161791446da6ea95a5bf87fdc64/src/com/wakatime/intellij/plugin/Dependencies.java#L131).~~ now using new Go wakatime-cli
* [ ] HBuilder X - **Do not download cli and the documentation is is Chinese**. [ref here](https://github.com/ZimoLoveShuang/hbuilderx-wakatime/blob/main/extension.js).
* [x] ~~IntelliJ IDEA - Downloads a zipped file from S3. [ref here](https://github.com/wakatime/jetbrains-wakatime/blob/786ab90f99bb8161791446da6ea95a5bf87fdc64/src/com/wakatime/intellij/plugin/Dependencies.java#L131).~~ now using new Go wakatime-cli
* [ ] Kakoune - Dowloads a zipped file from wakatime repo. [ref here](https://github.com/WhatNodyn/kakoune-wakatime/blob/master/wakatime.kak#L110).
* [ ] Kate - **Do not download cli**. [ref here](https://github.com/wakatime/kate-wakatime/blob/master/wakatimeplugin.cpp).
* [ ] Komodo - It embeds wakatime into `Componentes/wakatime` folder. [ref here](https://github.com/wakatime/komodo-wakatime).
* [x] ~~Micro - Downloads a zipped file from S3. [ref here](https://github.com/wakatime/micro-wakatime/blob/master/wakatime.lua#L145).~~ now using new Go wakatime-cli
* [x] ~~MonoDevelop - **Do not download cli**. [ref here](https://github.com/CodeCavePro/monodevelop-wakatime).~~ now using new Go wakatime-cli
* [x] ~~NetBeans - Downloads a zipped file from wakatime repo. [ref here](https://github.com/wakatime/netbeans-wakatime/blob/master/src/org/wakatime/netbeans/plugin/Dependencies.java#L148).~~ now using new Go wakatime-cli
* [x] ~~Notepad++ - Uses legacy Python cli via downloading GitHub master zip. [ref here](https://github.com/wakatime/notepadpp-wakatime/blob/master/WakaTime/Dependencies.cs#L39).~~ now using new Go wakatime-cli
* [x] ~~Nova - Downloads a zipped file from S3. [ref here](https://github.com/wakatime/WakaTime.novaextension/blob/70242000862ed86071c4d4ad969a1be3a543d887/Scripts/main.js#L91).~~ now using new Go wakatime-cli
* [x] ~~PhpStorm - Downloads a zipped file from S3. [ref here](https://github.com/wakatime/jetbrains-wakatime/blob/786ab90f99bb8161791446da6ea95a5bf87fdc64/src/com/wakatime/intellij/plugin/Dependencies.java#L131).~~ now using new Go wakatime-cli
* [x] ~~Powerpoint - Downloads a zipped file from S3. [ref here](https://github.com/wakatime/nuget-wakatime-shared-extension-utils/blob/master/src/WakaTime.Shared.ExtensionUtils/Dependencies.cs#L50).~~ now using new Go wakatime-cli
* [ ] Processing - Downloads legacy python cli from GitHub. [ref here](https://github.com/devgianlu/processing-wakatime/blob/master/src/main/java/xyz/gianlu/wakatime/processing/Dependencies.java#L203).
* [x] ~~PyCharm - Downloads a zipped file from S3. [ref here](https://github.com/wakatime/jetbrains-wakatime/blob/786ab90f99bb8161791446da6ea95a5bf87fdc64/src/com/wakatime/intellij/plugin/Dependencies.java#L131).~~ now using new Go wakatime-cli
* [x] Pymakr - Downloads legacy python cli from GitHub. [ref here](https://github.com/wakatime/eric6-wakatime/blob/master/PluginWakaTime.py#L380).
* [x] ~~Rider - Downloads a zipped file from S3. [ref here](https://github.com/wakatime/jetbrains-wakatime/blob/786ab90f99bb8161791446da6ea95a5bf87fdc64/src/com/wakatime/intellij/plugin/Dependencies.java#L131).~~ now using new Go wakatime-cli
* [x] ~~RubyMine - Downloads a zipped file from S3. [ref here](https://github.com/wakatime/jetbrains-wakatime/blob/786ab90f99bb8161791446da6ea95a5bf87fdc64/src/com/wakatime/intellij/plugin/Dependencies.java#L131).~~ now using new Go wakatime-cli
* [x] ~~Sketch - It embeds wakatime into `Resources/wakatime` folder. [ref here](https://github.com/wakatime/sketch-wakatime/tree/master/WakaTime.sketchplugin/Contents).~~ now using new Go wakatime-cli
* [ ] SlickEdit - **Do not download cli**. [ref here](https://github.com/wakatime/se_wakatime/blob/main/wakatime.e)
* [x] ~~SQL Server Management Studio - Downloads a zipped file from wakatime repo. [ref here](https://github.com/gandarez/ssms-wakatime/blob/master/WakaTime/Dependencies.cs#L38).~~ now using new Go wakatime-cli
* [x] ~~Sublime Text - Downloads a zipped file from S3. [ref here](https://github.com/wakatime/sublime-wakatime/blob/master/WakaTime.py#L567).~~ now using new Go wakatime-cli
* [x] ~~Terminal - **Do not download cli**. [ref here](https://github.com/wbingli/zsh-wakatime).~~ now using new Go wakatime-cli via updated install instructions
* [x] ~~TeXstudio - **Do not download cli**. [ref here](https://github.com/wakatime/texstudio-wakatime).~~ now using new Go wakatime-cli
* [ ] TextMate - Downloads legacy python cli from GitHub. [ref here](https://github.com/wakatime/textmate-wakatime/blob/master/WakaTime.mm#L60).
* [ ] Unity - It embeds wakatime into `client` folder which is a submodule to wakatime gh repo. [ref here](https://github.com/codeserk/wakatime-unity/tree/master/Editor/WakaTime).
* [x] ~~Vim - It embeds wakatime into `packages/wakatime` folder. [ref here](https://github.com/wakatime/vim-wakatime).~~ now using new Go wakatime-cli
* [x] ~~Visual Studio - Downloads a zipped file from S3. [ref here](https://github.com/wakatime/nuget-wakatime-shared-extension-utils/blob/master/src/WakaTime.Shared.ExtensionUtils/Dependencies.cs#L50).~~ now using new Go wakatime-cli
* [x] ~~VS Code - Downloads either from wakatime repo or S3 deppending on standalone flag. [ref here](https://github.com/wakatime/vscode-wakatime/blob/master/src/dependencies.ts#L29).~~ now using new Go wakatime-cli
* [x] ~~WebStorm - Downloads a zipped file from S3. [ref here](https://github.com/wakatime/jetbrains-wakatime/blob/786ab90f99bb8161791446da6ea95a5bf87fdc64/src/com/wakatime/intellij/plugin/Dependencies.java#L131).~~ now using new Go wakatime-cli
* [x] ~~Word - Downloads a zipped file from S3. [ref here](https://github.com/wakatime/nuget-wakatime-shared-extension-utils/blob/master/src/WakaTime.Shared.ExtensionUtils/Dependencies.cs#L50).~~ now using new Go wakatime-cli
* [ ] WPS Office - *Do not download cli and the documentation is is Chinese**. [ref here](https://github.com/ZimoLoveShuang/wps-wakatime/blob/main/js/ribbon.js).
* [x] Xamarin - **Do not download cli**. [ref here](https://github.com/CodeCavePro/monodevelop-wakatime).
* [x] ~~Xcode - Downloads a zipped file from S3. [ref here](https://github.com/wakatime/xcode-wakatime/tree/master/WakaTime).~~ now using new Go wakatime-cli

**Comment by shanreta** [comment]
Wing 9 or 10 IDE does not work with wakatime
