### ISSUE TITLE
Remove extra-heartbeats feature

### ISSUE THREAD

**Issue by gandarez** [wakatime/wakatime-cli#171]
The cli could have the ability of enqueuing heartbeats instead of letting this dirty job to the editors. It also implies to control debounce time.

**Comment by alanhamlett** [comment]
The reason for IDE plugins to queue heartbeats is to prevent spawning/forking too many processes in a short amount of time. In some cases, there could be thousands of heartbeats generated per second, and we risk using up the machine's RAM with too many processes. Also, using extra heartbeats means wakatime-cli can bundle heartbeats into one http request when sending to the API.
