### ISSUE TITLE
Error parsing config file

### ISSUE THREAD

**Issue by gandarez** [wakatime/wakatime-cli#360]
Windows user reported an error when parsing configuration file.

![Screenshot 2021-05-05 231646](https://user-images.githubusercontent.com/782854/117318779-bca1af80-ae58-11eb-96cf-8eda3f7431ab.png)

**Comment by alanhamlett** [comment]
Looks like it's fixed, but not sure why:
https://www.reddit.com/r/WakaTime/comments/n5ujt9/wakatime_error_vscode/gyaexzk

We should keep an eye out for this in case it's still happening, but will close for now.

**Comment by alanhamlett** [comment]
We needed to ``strings.Trim(param, `'"`)`` from `--config` because there were extra quotes wrapping that argument due to a space in the file path.
