### ISSUE TITLE
wakatime CLI being called multiple times and causing High CPU and Memory

### ISSUE THREAD

**Issue by glennsarti** [wakatime/wakatime-cli#363]
The wakatime extension appears to be calling the API many times over and causing very high cpu usage and memory consumption

![image](https://user-images.githubusercontent.com/5819622/117251659-8e7f9800-ae77-11eb-80f6-753e45fdf261.png)

Using wakatime 7.0.2

![image](https://user-images.githubusercontent.com/5819622/117251856-c8e93500-ae77-11eb-8e10-1e99f0ccfe1c.png)

**Comment by alanhamlett** [comment]
@glennsarti can you add this to your `~/.wakatime.cfg` file under `[settings]`:

```
legacy_python_cli = false
alpha = true
```

After adding those 2 lines, reload vscode and see if that fixes it for you?

**Comment by alanhamlett** [comment]
Fixed with #364 and released in v1.6.0.

**Comment by glennsarti** [comment]
Thanks @alanhamlett !
