### ISSUE TITLE
Log to multiple writers

### ISSUE THREAD

**Issue by gandarez** [wakatime/wakatime-cli#367]
The current implementation of wakatime-cli writes log to file or to standard output by setting to true `log-to-stdout`. The idea here is to discuss a more flexible approach by allowing users/devs to determine where to write logs.

My initial proposal here is to remove `log-to-stdout` and replace by `log-output` where it can accept multiple values as:

- `1` - it will log to file as it is
- `2` - it will log to standard output

Example
```bash
./wakatime-cli --log-output 1,2
```
If the parameter is not passed the defaut behaviour is to output to file.

**Comment by alanhamlett** [comment]
Is this still needed?
