### ISSUE TITLE
Stop creating project files

### ISSUE THREAD

**Issue by muety** [wakatime/wakatime-cli#380]
WakaTime keeps creating `.wakatime-project` files with project names like `Black Forest 77` in my projects. If I delete one, a new one is created. How can I stop that? Happens in IntelliJ, but I'm pretty sure I saw it in VSCode, too.

**Comment by alanhamlett** [comment]
Delete the `hide_project_names` line from your `~/.wakatime.cfg` file. More info at https://github.com/wakatime/wakatime-cli/blob/develop/CONFIGURING.md#settings-section.
