### ISSUE TITLE
New api_base_url config, keeping legacy api_url config unchanged for backwards compatibility

### ISSUE THREAD

**Issue by muety** [wakatime/wakatime-cli#384]
Someone just brought up this issue https://github.com/muety/wakapi/issues/203 in Wakapi. It looks like the format of the `api_url` as configured in `~/.wakatime.cfg` has changed and is now supposed to be `/api` instead of `/api/heartbeat`, is that correct?

This is not particularly a bug report, but rather I'm looking for ideas on how to gracefully migrate existing users' setups, who use custom `api_url`s, to this new version.

**Comment by gandarez** [comment]
Hi @muety,

The url for the heartbeat hasn't changed it still the same `https://api.wakatime.com/api/v1/users/current/heartbeats.bulk`.

**Comment by alanhamlett** [comment]
We'll fix this on our end. Commented [here](https://github.com/muety/wakapi/issues/203#issuecomment-844537058) too.
