### ISSUE TITLE
Improve release changelog quality

### ISSUE THREAD

**Issue by dron22** [wakatime/wakatime-cli#418]
Currently the changelog consists of all commit messages of the merged in changes.

![changelog](https://user-images.githubusercontent.com/17914254/119576025-42f64500-bdb8-11eb-9889-fa334a223485.jpg)
 
This might be useful for alpha releases, but a lot of time has no meaning for people not involved in the development. Also the amount of messages can obfuscate the important info.

At least for the official releases, changelog info quality should be improved

**Comment by gandarez** [comment]
I'm still working in this since I've been trying the best solution here. I'll come back soon with news.
