### ISSUE TITLE
Include wakatime-cli version in every log line output

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/wakatime-cli#424]
Every log output should include the wakatime-cli version, so we don't need to ask for it when debugging error messages.

**Comment by gandarez** [comment]
For reference
```{"caller":"/home/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/today/today.go:44","func":"Run","level":"fatal","message":"failed fetching summaries from api: failed to make request to \"https://api.wakatime.com/api/v1/users/current/summaries\": Get \"https://api.wakatime.com/api/v1/users/current/summaries?end=2021-05-27&start=2021-05-27\": x509: certificate signed by unknown authority","now":"2021-05-27T12:01:41+05:30","version":""}```
