### ISSUE TITLE
Files with custom rules don't get tracked anymore

### ISSUE THREAD

**Issue by TobiDimmel** [wakatime/wakatime-cli#445]
**Expected behavior (what you expected to happen)**:

I have some custom rules to distinguish the time I spend writing production code and test code.
![image](https://user-images.githubusercontent.com/2879214/120892192-5356bd00-c60d-11eb-83e2-9c6e460823dd.png)
I expect wakatime to track all files and set the category accordingly.

**Actual behavior (what actually happened)**:

This used to work perfect, but for some time (weeks or months) wakatime seems to not track the test files anymore.
The following screenshot shows the tracked files of a project of one day. I mostly wrote tests for _data-table.component.ts_, but the corresponding _data-table.component.spec.ts_ file is not tracked. I observed the same behaviour with my C# files.
![image](https://user-images.githubusercontent.com/2879214/120892340-19d28180-c60e-11eb-9e28-a86172bf80d3.png)

**Environment**:

- wakatime-cli version: VS Code extension (v12.0.0), Visual Studio extension (v10.3.1, cli v13.0.7)
- OS/Arch: Windows 10 20H2

**Anything else we should know?**:

no

**Comment by alanhamlett** [comment]
If you turn on debug mode (Ctrl + Shift + P then search `wakatime debug`) are there any error messages in your `~/.wakatime.log` file or vscode dev console window?

**Comment by TobiDimmel** [comment]
[wakatime.log](https://github.com/wakatime/wakatime-cli/files/6610062/wakatime.log) is the log file of today.

**Comment by alanhamlett** [comment]
Fixed in our API. Please send an email to alan@wakatime.com if you would like help reproducing your code stats from your log file.
