### ISSUE TITLE
Not working in WSL

### ISSUE THREAD

**Issue by aravindvnair99** [wakatime/wakatime-cli#457]
I followed the instructions mentioned at https://wakatime.com/terminal but I get the following error on WSL:

```console
: command not found
bash: /home/<username here>/bash-wakatime.sh: line 12: syntax error near unexpected token `$'{\r''
'ash: /home/<username here>/bash-wakatime.sh: line 12: `pre_prompt_command() {
```

This used to work fine in Git Bash. I recently came over to WSL2 and I am unable to get it to work.

**Comment by gandarez** [comment]
Hi, which linux distro have you installed?

**Comment by alanhamlett** [comment]
Duplicate of https://github.com/irondoge/bash-wakatime/issues/13.

**Comment by aravindvnair99** [comment]
> Hi, which linux distro have you installed?

@gandarez I have Ubuntu.
