### ISSUE TITLE
Waiting for wakatime plugins in repl.it IDE

### ISSUE THREAD

**Issue by sudip-mondal-2002** [wakatime/wakatime-cli#458]
Eagerly waiting for repl.it plugin
As many institutes does the lab works on repl.it, it should be beneficial to track the coding time.

**Comment by hiyorijl** [comment]
also wanting this, since repl.it is getting AI, collaborating with google cloud and everything. it's time.

**Comment by alanhamlett** [comment]
Duplicate of #942
