### ISSUE TITLE
New command line argument `--offline-count` to print number of heartbeats currently in offline db

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/wakatime-cli#462]
For ex:

```
$ wakatime-cli --offline-count
94
```

**Comment by gandarez** [comment]
What's the purpose for this?

**Comment by alanhamlett** [comment]
To inspect the offline db. Sometimes when debugging we ask how many heartbeats are in the offline db. Previously people would have to use sqlite command line to find out, but that's harder with boltdb.

**Comment by gandarez** [comment]
I'd like to take this task.
