### ISSUE TITLE
Include another configuration file

### ISSUE THREAD

**Issue by spywhere** [wakatime/wakatime-cli#464]
**Is your feature request related to a problem? Please describe.**

Normally, I have my configurations store as a repository on GitHub. And as you already know, storing passwords or secrets on public repository is a very bad practice. However, I would like to have my configurations stored on the repository still.

**Describe the solution you'd like to see**

Another configuration option (something like `config_file` or `extensions`, as `include` is already taken) for including another configuration file. So that I can keep my configurations separate from the secrets / API key. Or an option (something like `api_file`) to have it read / store from somewhere else is also fine for my use case.

**Describe alternatives you've considered**

Not yet explore, but so far this is the intuitive solution for me.

**Additional context**

None

**Comment by alanhamlett** [comment]
Let's call it `import_cfg` or `config_file`:

```INI
[settings]
import_cfg = path/to/secret.cfg
```

The imported INI file needs to still have a `[settings]` section. The imported cfg will be parsed and it's section's keys merged into existing configs, overwriting any already existing.

We also need to update the plugins to:
* read imported configs, so they don't prompt for an api key when one isn't set in the main parent config
* when updating the api key, the plugin needs to support writing to an imported config if `api_key` is already defined there
