### ISSUE TITLE
.wakatime-project no longer being used for project name when hide_project_names is true

### ISSUE THREAD

**Issue by Nonpareille** [wakatime/wakatime-cli#497]
**Expected behavior (what you expected to happen)**:
1. set hide project names to true in wakatime.cfg
2. set project name in .wakatime-project file
3. project name stays constant in file and is used for heartbeat

**Actual behavior (what actually happened)**:
project name in .wakatime-project file changes rapidly and setting manually gets ignored. Account is spammed with heartbeats from new randomly generated project names.

**Environment**:

- wakatime-cli version: v1.18.9
- OS/Arch: Windows 10/x86
- plugin: vscode

**Anything else we should know?**:
This set up was working fine until at least July 2nd.

**Comment by Nonpareille** [comment]
As a part of this issue my account was spammed with new projects with 0 time spent in them
![image](https://user-images.githubusercontent.com/3220546/124698132-016bb600-de9d-11eb-8abe-6f4329915eaa.png)

**Comment by alanhamlett** [comment]
This is caused by the new Go wakatime-cli recently launched. I've just rolled it back, so if you restart vscode it will work normally again.

**Comment by Nonpareille** [comment]
Perfect, just updated the extension and things are working again. Thank you for the quick turnaround!

**Comment by alanhamlett** [comment]
Let's leave this issue open until it's fixed in Go wakatime-cli.
