### ISSUE TITLE
Feature Request: Build and Restore time tracking.

### ISSUE THREAD

**Issue by BreakPointSoftware** [wakatime/wakatime-cli#503]
I can't see that out of the box, this addon tracks build a time tracking or Nuget Restore time tracking.   I would personally find this helps to keep track of how much of my day is being lost on compiling my projects and Restoring Nuget packages.

Can it be extended to support this?

Many thanks,
Gregs

**Comment by gandarez** [comment]
Hi @BreakPointSoftware,

If you're using VS for Windows it can detect how much time you're building, coding or debugging the project. Unfortunately there's no way to hook up nuget events.
