### ISSUE TITLE
Not working on network share

### ISSUE THREAD

**Issue by fabianneufang** [wakatime/wakatime-cli#504]
Hey.
The plugin works fine on a local drive, but when I am trying to use a network share, the dashboard does not show the project.

I attached the idea.log here. I am sorry for all the discord messages in there
[idea.log](https://github.com/wakatime/jetbrains-wakatime/files/5074953/idea.log)

Thank you
Fabian

**Comment by gandarez** [comment]
Hi @fabianneufang,

I didn't see any error at the log you attached. Would you mind consider updating WakaTime version in you IDE and check again if it happens?

**Comment by fabianneufang** [comment]
Hello @gandarez,

I am sorry, I don't even remember this issue anymore 😅

In the meantime, I neither use WakaTime nor JetBrains anymore. 

Have a nice day
Fabian
