### ISSUE TITLE
coding with ftp (Deployment) wakatime not working

### ISSUE THREAD

**Issue by nerdpanda-ir** [wakatime/wakatime-cli#505]
hi 
im edit files from ftp connection in (Php Storm)
but wakatime is not working !!!!
and Does not count working time

**Comment by gandarez** [comment]
Hi @nerdpanda-ir,

Does your ftp requires authentication?

**Comment by gandarez** [comment]
Hi we've launched support to FTP and SSH files. Please would you mind testing it again?
