### ISSUE TITLE
Time to commit only for master branch

### ISSUE THREAD

**Issue by toptalo** [wakatime/wakatime-cli#506]
1 - create new branch
2 - make changes
3 - commit & push (commit A)
4 - return to master branch
5 - make changes
6 - commit & push  (commit B)
7 - go to wakatime commits page

You will not see `commit A` but can see `commit B` with time `commit A time + commit B time`

git graph:
![image](https://user-images.githubusercontent.com/2378757/51521484-c8a80580-1e37-11e9-85c4-f5e488613bce.png)

wakatime commits:
![image](https://user-images.githubusercontent.com/2378757/51521602-1d4b8080-1e38-11e9-880e-29c4c61d2780.png)

I use WebStorm wakatime plugin and self hosted Gitlab

**Comment by gandarez** [comment]
Since we've updated to `wakatime-cli` based in Go would you mind testing it again and see if it gets fixed?
