### ISSUE TITLE
Getting error 405 while sending heartbeats

### ISSUE THREAD

**Issue by SqrtMinusOne** [wakatime/wakatime-cli#509]
I'm trying to use wakatime-mode with the new wakatime-cli. But for some reason, both new and old client have started to fail yesterday.

To reproduce, I've been running this command a number of times:
```
"/home/pavel/bin/wakatime-cli" --entity "/home/pavel/hello-world.txt" --plugin "emacs-wakatime/1.0.2" --time (date +%s) --verbose
```
**Expected behavior (what you expected to happen)**:
I expect the command to send the heartbeat to the WakaTime API. The number of heartbeats at https://wakatime.com/api/v1/users/current/heartbeats?date=2021-08-18 should increase by 1.

**Actual behavior (what actually happened)**:
| Attempt # | Timestamp  | Execution time | Exit code | Changes       | Saved? |
|-----------|------------|----------------|-----------|---------------|--------|
| 1         | 1629275658 | 1m 1s          | 1         | None          | +      |
| 2         | 1629275801 | 41s            | 0         | +2 heartbeats | +      |
| 3         | 1629275906 | 1m 1s          | 1         | None          | +      |
| 4         | 1629275996 | 2s             | 102       | None          |        |
| 5         | 1629276030 | 1m 1s          | 102       | None          |        |
| 6         | 1629276228 | 59s            | 0         | +2 heartbeats | +      |
| 7         | 1629276318 | 2m             | 1         | None          | +      |
| 8         | 1629276476 | 1m 1s          | 1         | None          | +      |
| 9         | 1629276553 | 2m             | 1         | +2 heartbeats | +      |
| 10        | 1629276720 | 2s             | 102       | None          |        |
| 11        | 1629276748 | 1m 41s         | 1         | +2 heartbeats | +      |

More often than not the command fails. Some heartbeats are even lost.

The most frequent message in `.wakatime.log` looks as follows:
```
{"caller":"/home/pavel/Code/wakatime-cli/cmd/legacy/run.go:194","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s) due to api error: failed to send heartbeats via api client: invalid response status from \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\". got: 405, want: 201/202. body: \"<html>\\r\\n<head><title>405 Not Allowed</title></head>\\r\\n<body>\\r\\n<center><h1>405 Not Allowed</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n\"","now":"2021-08-18T11:52:01+03:00","version":"unset"}
```

It looks like nginx at your side returns 405 for some reason.

**Environment**:

- wakatime-cli version: 19bc5a41bdff75ecb3ae9d51d55d4b2714fc7042
- OS/Arch: GNU Guix 1.3

If that helps, my IP at the moment is 95.153.32.93

**Anything else we should know?**:
Full log file: [wakatime.log](https://github.com/wakatime/wakatime-cli/files/7005936/wakatime.log)

**Comment by alanhamlett** [comment]
Nothing to worry about since code stats are saved locally until they can sync. We're having higher than normal load on our API this week.

**Comment by SqrtMinusOne** [comment]
OK, thanks. Then I'll send a PR to wakatime-mode to ignore these errors a bit later, because Emacs lags whenever `error` is called from a process sentinel.

**Comment by alanhamlett** [comment]
What does `Saved?` column mean?

**Comment by SqrtMinusOne** [comment]
The `Saved` column shows whether the heartbeat was saved, i.e. did I found a heartbeat with a particular timestamp in the API response for that day. It seems like some heartbeats were lost, but I don't think it affects the statistics in any significant way.

**Comment by alanhamlett** [comment]
This should be fixed in the latest version?

**Comment by gandarez** [comment]
@SqrtMinusOne Could you confirm if it's fixed?

**Comment by SqrtMinusOne** [comment]
Yes, I've just checked and it seems to work fine. Thank you!

Also sorry for the delay, somehow missed the previous notice.
