### ISSUE TITLE
Wakatime  dashboard explanations are not visible

### ISSUE THREAD

**Issue by bahadiraraz** [wakatime/wakatime-cli#520]
![image](https://user-images.githubusercontent.com/48323786/131265030-6ca7c931-9e61-42d3-994c-ff5b7585a018.png)

for a few days, the explanations are not visible on the wakatime dashboard

**Environment**:

- wakatime-cli version:
- web

**Anything else we should know?**:

**Comment by alanhamlett** [comment]
Thanks, it's fixed 👍
