### ISSUE TITLE
Suggestion: Count editing of Snakemake files as python, or as Snakemake, rather than other

### ISSUE THREAD

**Issue by iamh2o** [wakatime/wakatime-cli#522]
**Is your feature request related to a problem? Please describe.**
No problem per se, but a desire to see a place a fair number of Scientist programmers spend their time counted.

**Describe the solution you'd like to see**
Simply account for the time  spent editing files named 'Snakefile', or which end in *.smk to be python/Snakemake (ideally the latter).

**Describe alternatives you've considered**
No alternatives come to mind, I don't expect this will be a hard feature to expose, if it's really just recognizing the file types.

**Additional context**
Snakemake is unarguably the most utilized  (or possibly... possibly second) analysis workflow automation language/tool in use today.  At this point over 5000 Scientific publications have cited [Snakemake](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8114187/) , with 5 new publications a day.   The other tools largely do not even register 100s.  And this is a demonstration of massive adoption.   I think a large number of people would find having this granulized into the dashboards (and count towards leaderboards)

**Comment by alanhamlett** [comment]
Detecting `*.smk` files as `Snakemake` language now. Thanks!

**Comment by iamh2o** [comment]
This is awesome. Thank you. There is a minor tweak I think is needed to round this out.  Snakemake files are either called simply 'Snakefile', or *.smk (including Snakefile.smk).  But many Snakemake folks do most of their work in a top level file simply called Snakefile, with no extension.  Just want to be sure those are caught too.  Thanks again---
john

**Comment by alanhamlett** [comment]
Got it, just added support for files ending with `/Snakefile` (case-insensitive) to be detected as `Snakemake` language.

**Comment by iamh2o** [comment]
rock.  thanks!
