### ISSUE TITLE
Reformatting language options

### ISSUE THREAD

**Issue by michalspano** [wakatime/wakatime-cli#527]
**Is your feature request related to a problem? Please describe.**

I have been using Wakatime Stats for some time. I primarily use __ZSH__ locally on my Mac machine.  However, under __languages section__ it happens to be displayed in the __others__ section (which might get a bit confusing after some time).

**Describe the solution you'd like to see**

I'd like to ask (or propose) a possibility to rename or reformat a certain language in Wakatime stats dashboard. 
E.g. __.zsh__ to be displayed as `ZSH` (as seen in the Editor's section) instead of __Others__.

![scr](https://user-images.githubusercontent.com/71947840/131710738-8038c7a1-c620-42f9-a300-e575fc6c92c2.png)

**Describe alternatives you've considered**

>

**Additional context**

I am using `iTerm` configured with __zsh__, local wakatime CLI;
```
[internal]
cli_version = v1.22.0
```
And the __Wakatime ZSH plugin__ at `.zshrc`:

```
plugins=(
git
...
zsh-wakatime)
```

PS. I am a big fan of Wakatime and appreciate the team's effort! :blush:

**Comment by alanhamlett** [comment]
The easiest way to do this is with a [Custom Rule](https://wakatime.com/faq#language-not-detected):

If file ends with `.zsh` then change language to `ZSH`.

**Comment by michalspano** [comment]
Thanks for your input @alanhamlett!

**Comment by michalspano** [comment]
Returning to #527
I managed to __fix__ this by [overriding behaviour](https://wakatime.com/settings/rules) as follows:

```
If 'Language' 'equals' 'Other'
-> then change 'Language' to Zsh
```

I realized that any `.zsh` file by itself would get detected by __Languages__. However, __Zsh__ ([per this usage](https://wakatime.com/terminal)) has been configured to be to an __IDE__ (not a language explicitly). Therefore, to use __Zsh__ both as an IDE and a language, one must follow such __override__.

![screen](https://user-images.githubusercontent.com/71947840/132089635-090faeb7-b5db-4f18-9b33-3222dff76faa.png)
\- Works as expected now

__Alternative__: configure Wakatime for __iTerm__ (instead of Zsh) [link](https://wakatime.com/terminal#install-iterm2).

I hope someone (experiencing a similar issue) might find this helpful. 😊 

PS. Thanks @alanhamlett for guidance.

**Comment by alanhamlett** [comment]
It's best not to match `Other` language, especially if your files all end with `.zsh`. That way you won't accidentally change the language for non-zsh files sometime in the future.

**Comment by michalspano** [comment]
That is definitely true, such behaviour will indeed override other __non-zsh__ files. 

Henceforth, configuring __Wakatime for iTerm__ will do the job in this case and will detect __Zsh__ automatically.

__Background:__
I, in fact, tried your mentioned solution, and it did not seem to work: 

![screen2](https://user-images.githubusercontent.com/71947840/132090401-ceca0123-82bc-4231-a176-40c96f27d66e.png)

(Shortly, running [as an IDE] __Zsh__ does not directly involve running `.zsh` files, thus no language detection).



> Returning to #527
> I managed to **fix** this by [overriding behaviour](https://wakatime.com/settings/rules) as follows:
> 
> ```
> If 'Language' 'equals' 'Other'
> -> then change 'Language' to Zsh
> ```
> 
> I realized that any `.zsh` file by itself would get detected by **Languages**. However, **Zsh** ([per this usage](https://wakatime.com/terminal)) has been configured to be to an **IDE** (not a language explicitly). Therefore, to use **Zsh** both as an IDE and a language, one must follow such **override**.
> 
> ![screen](https://user-images.githubusercontent.com/71947840/132089635-090faeb7-b5db-4f18-9b33-3222dff76faa.png)
> - Works as expected now
> 
> **Alternative**: configure Wakatime for **iTerm** (instead of Zsh) [link](https://wakatime.com/terminal#install-iterm2).
> 
> I hope someone (experiencing a similar issue) might find this helpful. 😊
> 
> PS. Thanks @alanhamlett for guidance.

**Comment by michalspano** [comment]
__In conclusion of #527__
1. Configure Wakatime for iTerm (recognized Zsh detection)
2. Implement [Custom rules](https://wakatime.com/faq#language-not-detected)
