### ISSUE TITLE
go-ini writer with multiline values breaks legacy wakatime-cli for Vim

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/wakatime-cli#532]
**Bug description**

If go-ini modifies any key in `~/.wakatime.cfg`, a side effect is every key gets parsed and re-written to the cfg file. If the cfg file contains a multiline value, that incorrectly gets written without indentation. Then when any legacy Python wakatime-cli reads the cfg file, it causes a crash:
```
Traceback (most recent call last):
  File "/wakatime/configs.py", line 58, in parseConfigFile
    configs.read_file(fh)
  File "/wakatime/packages/configparser/__init__.py", line 724, in read_file
    self._read(f, source)
  File "/wakatime/packages/configparser/__init__.py", line 1131, in _read
    raise e
ParsingError: Source contains parsing errors: '~/.wakatime.cfg'
	[line  3]: u'COMMIT_EDITMSG$\n'
	[line  4]: u'PULLREQ_EDITMSG$\n'
	[line  5]: u'MERGE_MSG$\n'
	[line  6]: u'TAG_EDITMSG$"""\n'
```

Example `~/.wakatime.cfg` file that causes the error:
```
[settings]
ignore             = """
COMMIT_EDITMSG$
PULLREQ_EDITMSG$
MERGE_MSG$
TAG_EDITMSG$"""
status_bar_enabled = true
debug=true
[internal]
cli_version = v1.22.1
cli_version_last_modified = Wed, 01 Sep 2021 21:48:38 GMT
backoff_retries           = 0
backoff_at                =
```

Example `~/.wakatime.cfg` file that does NOT cause the error:
```
[settings]
ignore             = """
 COMMIT_EDITMSG$
 PULLREQ_EDITMSG$
 MERGE_MSG$
 TAG_EDITMSG$"""
status_bar_enabled = true
debug=true
[internal]
cli_version = v1.22.1
cli_version_last_modified = Wed, 01 Sep 2021 21:48:38 GMT
backoff_retries           = 0
backoff_at                =
```

The only change is indenting the multiline `ignore` value with one space before each line.

**Comment by AbhJ** [comment]
When does go-ini modify keys in `~/.wakatime.cfg`? Like it does when vs code sends heartbeat right?

**Comment by alanhamlett** [comment]
> When does go-ini modify keys in ~/.wakatime.cfg? Like it does when vs code sends heartbeat right?

Go-ini modifies the cfg only when there was a connection error when sending code stats (heartbeats) to the api. It writes the two internal `backoff` settings, but the side effect causes it to modify multiline values as well.

**Comment by AbhJ** [comment]
Hey Alan, can you please say which files I need to go through, so that I get know more about the modification of the config file?
