### ISSUE TITLE
Order log output so "now" is always first key

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/wakatime-cli#536]
When reading log output from `~/.wakatime.log`, it would be nice for the keys to always have the same order. We should force `now` to be first, followed by `version`, `level`, `caller`, `func`, and finally `message`.

**Comment by gandarez** [comment]
There's already an open issue to discuss this topic https://github.com/wakatime/wakatime-cli/issues/346.

**Comment by alanhamlett** [comment]
Got it, closing as duplicate.
