### ISSUE TITLE
Replace the wakatime-cli in homebrew with the go version

### ISSUE THREAD

**Issue by ecafkoob** [wakatime/wakatime-cli#546]
Replace the python version of wakatime-cli with the golang version of wakatime-cli in homebrew.

**Describe the solution you'd like to see**

I can install the golang version of wakatime-cli via homebrew.

**Describe alternatives you've considered**

The go version of wakatime-cli is very small and is available for various platforms. I think it should not be very difficult to modify the formula.and then update homebrew formula.

**Comment by alanhamlett** [comment]
Homebrew now uses the Go wakatime-cli, which has a new binary name `wakatime-cli` instead of the old `wakatime`.
