### ISSUE TITLE
Download and installation instructions

### ISSUE THREAD

**Issue by Hermesiss** [wakatime/wakatime-cli#566]
Hi! I want to use a shiny new version, but "Creating a plugin" from readme doesn't contain instructions for it, only for Python.

There are several questions about it:

- Where can I download the latest version of the new cli?
- Are there any requirements for launching it?
- Any unusual steps during installation?

**Comment by gandarez** [comment]
Hi @Hermesiss, the documentation is outdated and needs some update on it. @alanhamlett we need to revamp the [documentation](https://wakatime.com/help/creating-plugin) after have launched wakatime-cli Go.

**Comment by alanhamlett** [comment]
Updated the `Creating a plugin` doc with latest instructions and code examples.
