### ISSUE TITLE
Any plans to suport a timezone setting?

### ISSUE THREAD

**Issue by fiote** [wakatime/wakatime-cli#571]
Request:
Add a timezone setting that accept timezone-strings as value (ex: America/Edmonton, Europe/Dublin, etc). So instead of uploading the time worked on my timezone, it would upload it on the specified one. This can be achieved by changing the timezone of my computer, but I kinda need it to be project-specific.

Reasoning:
Most of my work is done on 'local time', but some of it it's for a client in another timezone, and since I slice my payments on days worked sometimes my work 'session' goes through my midnight and messes with the payment calculation.

**Comment by gandarez** [comment]
@alanhamlett is this something we could do in the cli side? What about a new section `[timezone]` which is a key value pair of projects's path and olson timezone.

```ini
[timezone]
/usr/folder/project* = Europe/Dublin
/user/other/project* = America/Edmonton
```

**Comment by alanhamlett** [comment]
Timezone is a display-only thing. Better to improve the website to allow displaying projects in different time zones.

Or if we wait long enough, everyone in the solar system will use UTC and this won't be an issue.
