### ISSUE TITLE
Lock config files when reading/writing to prevent corruption

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/wakatime-cli#576]
Some recent bugs (wakatime/jetbrains-wakatime#192 and wakatime/vscode-wakatime#232) suggest that the `~/.wakatime.cfg` and `~/.wakatime-internal.cfg` files may become corrupted if two wakatime-cli processes write to the file at the same time. This is only a guess, so maybe something else is causing the files to become corrupted. However, it can't hurt to lock anytime we read/write those files to prevent clobbering them.

**Comment by alanhamlett** [comment]
Might be able to use [lockfile](https://pkg.go.dev/github.com/nightlyone/lockfile), if it supports writing to the locked file.

**Comment by alanhamlett** [comment]
Or, we can use bbolt's flock implementation since it's already working for the offline db:

https://github.com/etcd-io/bbolt/blob/7ee3ded59d4835e10f3e7d0f7603c42aa5e83820/bolt_unix.go#L12

(Along with each OS implementation of flock in that folder)

**Comment by gandarez** [comment]
@alanhamlett do you still have the original error and don't mind posting it here?

**Comment by alanhamlett** [comment]
Here's the related error from a user's screenshot:
![132372975-1b39d3f0-ff4f-4c43-b4a3-5c91c9ba34b8](https://user-images.githubusercontent.com/522344/143054112-497d260c-0550-4802-8b10-cb2f0decb64e.png)

**Comment by gandarez** [comment]
I don't believe locking it will prevent errors like that. After few researches and debugs I realized that error happened mostly  because the `api-key` key was formatted like the example below. The value `e39968` is the line content where it first found the error.

```ini
api-key = 1d2e89f0-27a3-4488-84d6-1f0e5
b18a040
```

In this case it would print `key-value delimiter not found: b18a040`. May we close this issue @alanhamlett?

**Comment by alanhamlett** [comment]
> I don't believe locking it will prevent errors like that. After few researches and debugs I realized that error happened mostly because the `api-key` key was formatted like the example below. The value `e39968` is the line content where it first found the error.
> 
> ```ini
> api-key = 1d2e89f0-27a3-4488-84d6-1f0e5
> b18a040
> ```

How does the value get the newline, because in these cases it was entered correctly but then somehow became corrupted without manually changed?


> In this case it would print `key-value delimiter not found: b18a040`. May we close this issue @alanhamlett?

Let's leave it open for now, because without file-level locking on writes it's still definitely possible to corrupt the file contents if two wakatime-cli processes write to the config file at the same time.
