### ISSUE TITLE
Config option to only send file paths relative to project folder

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/wakatime-cli#591]
### Discussed in https://github.com/wakatime/wakatime-cli/discussions/589

<div type='discussions-op-text'>

<sup>Originally posted by **kaushalyap** November 28, 2021</sup>
Currently it send absolute paths, I am aware of `hide_file_names option` As I think this obfuscate all file names, instead I want to obfuscate only the path to project, but still keep the filenames relative to the project directory ex: `{obfuscateted}/ProjectName/somefile.js`</div>

**Comment by alanhamlett** [comment]
@kaushalyap What should it send when no project folder is detected (Unknown Project in the dashboard)... the full file path?

**Comment by kawpii** [comment]
> @kaushalyap What should it send when no project folder is detected (Unknown Project in the dashboard)... the full file path?

file name with relative path would do ex: Directory/something.js

**Comment by alanhamlett** [comment]
I don't understand... how would we know the relative path without knowing the project folder?

**Comment by kawpii** [comment]
> I don't understand... how would we know the relative path without knowing the project folder?

just take the full path (ex: /home/username/some/thing/dir/something.js) but only send the dir/something.js to the server.

**Comment by alanhamlett** [comment]
What do we send when no project is detected? (`Unknown Project`)

Do we send the full file path, or just send the file name? We can't choose a path relative to the workspace directory because we don't know the workspace directory for `Unknown Project`.

@gandarez suggests we only send the file name in this case, sgtm.

We should also add `--project-folder` so we can send relative paths when using `--alternate-project` after the project folder wasn't able to be detected automatically.

**Comment by alanhamlett** [comment]
So, to summarize what's needed:

* new ini setting `relative_paths = false` (defaults to false, current behavior)
* new command line argument `--project-folder <workspace-path>` to be sent from IDE irregardless of the value of `relative_paths`
* new command line flag `--relative-paths` which when present, is the same as `relative_paths = true`; this probably won't be used same as `--hide-project-names` flag isn't used by the plugins because we get this value from the ini config file instead of plugins duplicating work

When `relative_paths = true`, we left-trim the absolute path removing `workspace-path`. Workspace path first comes from `--project-folder <workspace-path>` or uses the auto-detected project folder when no workspace path is passed from the IDE.

**Comment by kawpii** [comment]
@gandarez @alanhamlett Thanks! Great work!

When will be this update released with extensions / plugins?

**Comment by gandarez** [comment]
@kaushalyap as soon as it gets released https://github.com/wakatime/wakatime-cli/pull/617

**Comment by alanhamlett** [comment]
Once it shows up in [releases](https://github.com/wakatime/wakatime-cli/releases) you'll need to restart your editor to get the new version.

**Comment by kawpii** [comment]
@gandarez It seems that this change is not yet released?

**Comment by alanhamlett** [comment]
It was released in v1.32.1.
