### ISSUE TITLE
Adobe XD plugin exist for wakatime

### ISSUE THREAD

**Issue by yeasin50** [wakatime/wakatime-cli#614]
On [plugins](https://wakatime.com/plugins) section of [wakatime](https://wakatime.com/plugins), it is not available. 

![image](https://user-images.githubusercontent.com/46500228/147860374-95b7730a-d33b-4d59-8d84-b524844e1a0a.png)

You can  find the plugin here [adobe xd plugin](https://adobe.com/go/cc_plugins_discover_plugin?pluginId=391090dc&workflow=share)

Thought it would be better to notify

**Comment by gandarez** [comment]
We've no idea who's the maintainer and it's also not open source code.

**Comment by alanhamlett** [comment]
I'll reach out to the author and see if he can open source it, then we'll add it to the plugin list.

**Comment by alanhamlett** [comment]
Turns out it's actually from https://github.com/wakatime/adobe-xd-wakatime, so I'll publish it today.

**Comment by alanhamlett** [comment]
Will be published pending Adobe approval.

**Comment by yeasin50** [comment]
& thanks for creating wakatime.
