### ISSUE TITLE
A way to change config location.

### ISSUE THREAD

**Issue by tusqasi** [wakatime/wakatime-cli#626]
**Is your feature request related to a problem? Please describe.**
I can't find a way to change where wakatime stores its configuration files.
By default it stores everything in `$HOME`. I want to change its location, but can't find a way to do it.

**Describe the solution you'd like to see**
An environment variable would be very useful.

**Describe alternatives you've considered**
None so far, and symlinks is not a solution.

**Additional context**

OS: linux
Intergrations used: vim

**Comment by tusqasi** [comment]
ohhhh...  
I missed projects, it was there. You guys are already on it.
Ooops.

**Comment by alanhamlett** [comment]
You can use `$WAKATIME_HOME` to customize the config file location.
