### ISSUE TITLE
More sensible `$WAKATIME_HOME` default

### ISSUE THREAD

**Issue by kidonng** [wakatime/wakatime-cli#655]
**Is your feature request related to a problem? Please describe.**

> [`$WAKATIME_HOME` defaults to your user's `$HOME` directory.](https://github.com/wakatime/wakatime-cli/blob/develop/USAGE.md#:~:text=%24WAKATIME_HOME%20defaults%20to%20your%20user%27s%20%24HOME%20directory.)

Convenient, right? Until you come up with [the same question as many others have](https://github.com/search?q=org%3Awakatime+wakatime_home+is%3Aissue&type=issues):

```
$ ls -a ~ | grep wakatime
.wakatime
.wakatime-internal.cfg
.wakatime.bdb
.wakatime.cfg
.wakatime.data
.wakatime.log
```

So after some digging you find `$WAKATIME_HOME`, which is great except it is not obvious how to set environment variable in Windows and [especially macOS](https://stackoverflow.com/questions/135688/setting-environment-variables-on-os-x#:~:text=How%20to%20keeping%20changes%20after%20a%20reboot), which keeps the environment in [some obscure location](https://stackoverflow.com/a/70510488).

**Describe the solution you'd like to see**

`$WAKATIME_HOME` should have a more sensible default that doesn't clutter user's home directory, like `$XDG_CONFIG_HOME/wakatime` (where `$XDG_CONFIG_HOME` defaults to `$HOME/.config` if not set), or `$HOME/.wakatime` where the CLI is already stored.

**Describe alternatives you've considered**

Ask everyone to set `$WAKATIME_HOME` 🤷

**Additional context**

**Comment by alanhamlett** [comment]
How about we move all these files into the `~/.wakatime/` folder by default?

**Comment by nagromc** [comment]
Related to #558.

**Comment by kidonng** [comment]
@nagromc Oops, then this is more likely a duplicate.

But I'd really like to see this being pushed forward instead of waiting for 5 months 😅
