### ISSUE TITLE
Possible infinite loop

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/wakatime-cli#663]
Originally posted at https://twitter.com/Pruxis/status/1500798637571551232.

![image](https://user-images.githubusercontent.com/522344/157093143-2e53a9c3-348c-4d38-98c3-4afdebe29661.png)

**Comment by gandarez** [comment]
@alanhamlett don't think it's happening since nobody else has reported it.

**Comment by alanhamlett** [comment]
Let's leave it open until I look through the code for any loops or recursion that might never break or end, and add failsafe counters to them.

**Comment by gandarez** [comment]
It's not reported by any other user.
