### ISSUE TITLE
Time spent on commits from GitLab

### ISSUE THREAD

**Issue by frossigneux** [wakatime/wakatime-cli#668]
I have a Wakatime free account with gmail address, and linked my account to Github.
I have also a Gitlab account with my company address (with repositories of a Gitlab organization whose I am member).
My username is the same on Github and Gitlab.
I don't use yet organization feature on Wakatime.

I don't see the spent time on commits on my Gitlab organization.

So I found this issue: https://github.com/wakatime/legacy-python-cli/issues/71

> Just fixed this by looking up your GitLab username when unable to match a GitLab committer's email to a WakaTime account.
> GitLab doesn't show usernames for commits in their API, so we had to match the committer's email against your WakaTime email. Since your emails are different on GitLab and WakaTime, we weren't able to match your coding activity to your commits. It's fixed now by keeping a cache of emails to usernames.

I then changed my Wakatime email address to set the same email address on Wakatime and Gitlab.
Both tried by setting it in primary or backup email.
But no improvements.

Then I looked in the API to get the info of commit. I don't know if it is normal, but author_username, committer_username, committer_email are all null.

I think it's a username or email matching problem given that time are correctly displayed in dashboard as well as projects.

**Comment by alanhamlett** [comment]
Author and Committer usernames are only `null` when WakaTime couldn't find the author for that commit.

Send an email to support@wakatime.com so I can help debug this. Please include your GitHub or WakaTime username in the email.

**Comment by alanhamlett** [comment]
Showing time per commit for GitLab repos has been fixed today.
