### ISSUE TITLE
Auto-update

### ISSUE THREAD

**Issue by gandarez** [wakatime/wakatime-cli#72]
Make wakatime-cli be able to update its own binary without depending upon the user.

**Comment by dron22** [comment]
@alanhamlett This is already handled by the plugins, right? Once, they switch from wakatime py to wakatime-cli they will always pull the latest release, correct?

**Comment by gandarez** [comment]
Currently the majority of plugins updates wakatime when it's outdated. My idea here was to not wait for any IDE to do it but the cli could be smart enough and auto-update itself.

**Comment by alanhamlett** [comment]
That seems possible for the future, but not necessary in the first launch since the plugins already need to download wakatime-cli so the code is already implemented in the plugins.

**Comment by muety** [comment]
Just out of curiosity, what is the current state of the rollout of the new CLI? I think I'm still using the legacy version in both of my machines. How will the migration take place? Do you require the plugins maintainer's cooperation for this? And how can I tell whether I'm using the old or new CLI version except inspecting the user agent string as received at the server?

**Comment by alanhamlett** [comment]
> what is the current state of the rollout of the new CLI?

We're waiting to rollout until fixing this proxy issue #385 It's been difficult to fix, and might be a problem with Go's tls library.

> Do you require the plugins maintainer's cooperation for this?

We maintain most of the plugins, but a few community built plugins (like [this](https://github.com/CodeCavePro/monodevelop-wakatime)) will need the maintainer's help to switch to the new wakatime-cli.

> how can I tell whether I'm using the old or new CLI version

Easiest way is visit https://wakatime.com/api/v1/users/current/user_agents. The first item is the most recent plugin seen by wakatime, but might have up to 20 seconds lag. If "value" says Python then it's the old wakatime-cli. If it says Go, then it's the new cli.

**Comment by alanhamlett** [comment]
We've implemented auto-updating wakatime-cli in most plugins now, so we don't need to build it into wakatime-cli.
