### ISSUE TITLE
Having issues with hearbeat

### ISSUE THREAD

**Issue by mickeypash** [wakatime/wakatime-cli#759]
**Expected behavior (what should have happened)**:

I've been having issues with waka time reporting statistics.
I just did a fresh install. I realised I was running the older Python version of the CLI with the vim plugin.

**Actual behavior (what went wrong)**:

I would like to be able to see my stats in the dashboard.

**Environment**:

- OS: macOS Monterey Version 12.4
- Platform: i386

**Logs**:

```
{"caller":"pkg/heartbeat/format.go:61","func":"heartbeat.formatLinuxFilePath","level":"warning","message":"failed to resolve real path for \"/Users/myuser/[Plugins]\": lstat /Users/myuser/[Plugins]: no such file or directory","now":"2022-07-19T12:15:10+01:00","version":"v1.53.3"}
{"caller":"pkg/filter/filter.go:33","func":"filter.WithFiltering","level":"error","message":"filter file: skipping because of non-existing file \"/Users/myuser/[Plugins]\"","now":"2022-07-19T12:15:10+01:00","version":"v1.53.3"}

```

**Comment by gandarez** [comment]
Hi @mickeypash, 

Does that folder exist on your hard drive `/Users/myuser/[Plugins]`?

**Comment by alanhamlett** [comment]
That looks like some temporary buffer created by Vim. If you open a real file with Vim, does that time show on your dashboard?

**Comment by mickeypash** [comment]
Thanks for the response! It did work eventually. It was totally a user error!
