### ISSUE TITLE
Support for proxy env vars

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/wakatime-cli#764]
The legacy Python cli detected env vars `http_proxy`, `https_proxy`, `no_proxy`, and `all_proxy` with the [requests library](https://requests.readthedocs.io/en/latest/user/advanced/#proxies), we should too.

**Comment by kprav33n** [comment]
Thank you for accepting the feature request. It would be useful to honor the environment variables as the legacy Python client did. FWIW, the implementation could benefit from [golang.org/x/net/http/httpproxy](https://pkg.go.dev/golang.org/x/net/http/httpproxy) library.
