### ISSUE TITLE
Detect *.ps files as PowerShell unless contents contains %!PS

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/wakatime-cli#765]
PowerShell is more common than PostScript, but it looks like we detect PostScript before PowerShell when files end with `.ps`. To fix this, only detect PostScript when the contents contain `%!PS`, which is a PostScript comment. That should always work because...

> The character "%" is used to introduce comments in PostScript programs. As a general convention, every PostScript program should start with the characters "%!PS" as an [interpreter directive](https://en.wikipedia.org/wiki/Interpreter_directive) so that all devices will properly interpret it as PostScript.

https://en.wikipedia.org/wiki/PostScript#The_language

**Comment by gandarez** [comment]
PowerShell doesn't use the extension `.ps` and it seems it's only related to PostScript [[here](https://www.adobe.com/creativecloud/file-types/image/vector/ps-file.html#:~:text=frequently%20asked%20questions-,What%20is%20a%20PS%20file%3F,open%20it%20in%20an%20application.)]. Instead PowerShell should be saved as `.ps1`. Is this a real issue or a mistaken on user's side?

**Comment by alanhamlett** [comment]
Oh, you're right. Let's close this issue.
