### ISSUE TITLE
Microsoft Defender is blocking WakaTime...

### ISSUE THREAD

**Issue by zhangta** [wakatime/wakatime-cli#782]
OS: Win10 21H2 (19044.2130)
VSCode: 1.73.0 (system setup)
WakaTime: v21.0.0

![Snipaste_2022-11-06_19-05-53](https://user-images.githubusercontent.com/415229/200170905-88116062-1a0c-4d8c-826e-0b2dc0107823.png)

![Snipaste_2022-11-06_20-31-47](https://user-images.githubusercontent.com/415229/200170948-3823a124-d684-48b8-b27a-1db32908417b.png)

**Comment by alanhamlett** [comment]
What's the warning message from your VSCode dev console window?

**Comment by zhangta** [comment]
https://user-images.githubusercontent.com/415229/200206989-da8479bc-688c-4a9a-9afa-18b01172aecf.mp4

**Comment by alanhamlett** [comment]
That's not the dev console. To open the dev console, go to Help -> Toggle Developer Tools.

**Comment by zhangta** [comment]
Please take a look again.

![Snipaste_2022-11-07_19-59-12](https://user-images.githubusercontent.com/415229/200306976-5083b7ea-8c93-450a-ac4a-c6b2a5cf7d7e.jpg)

**Comment by alanhamlett** [comment]
Some things I noticed:

* your `wakatime.log` file shows wakatime-cli is executing (not blocked by Windows Defender)
* your `wakatime.log` file shows wakatime-cli can't connect to the WakaTime API
* your vscode dev console shows `spawn EPERM` when the plugin uses vscode's nodejs api to read the config file `~/.wakatime.cfg`

That means there's probably two separate issues here:
1. wakatime-cli unable to connect to the WakaTime API
2. the vscode plugin unable to read `~/.wakatime.cfg`

Can you check `Windows Firewall` and `Windows Defender` settings for recently blocked apps?
