### ISSUE TITLE
Buggy command to sync offline activties

### ISSUE THREAD

**Issue by makaveli404** [wakatime/wakatime-cli#809]
Hello.
I found a bug with the following command:
`~/.wakatime/wakatime-cli --sync-offline-activity none`

This probably should sync existing offline files to wakatime but it doesn't.
I mailed with Alan and I get very similar command:
`~/.wakatime/wakatime-cli --sync-offline-activity 9999` 
and he told me to report it as a bug :)

**Comment by alanhamlett** [comment]
Yea, `none` should make it sync all heartbeats without a limit. But the amount of people using it is probably low, so let's change it to `~/.wakatime/wakatime-cli --sync-offline-activity 0` where zero syncs all offline heartbeats without limit.
