### ISSUE TITLE
Consider consolidating dot files into the .wakatime directory

### ISSUE THREAD

**Issue by 2-5** [wakatime/wakatime-cli#825]
Currently on Windows WakaTime creates these files in the home directory:

```
.wakatime/wakatime-cli-windows-amd64.exe

.wakatime.bdb
.wakatime.cfg
.wakatime-internal.cfg
.wakatime.log
```

Consider moving the individual `.bdb`, `.cfg`, `.log` files into the `.wakatime` directory. Maybe keep just `.wakatime.cfg` outside to prevent breaking changes.

**Comment by alanhamlett** [comment]
Yes, it's on our todo list with #558.

**Comment by alanhamlett** [comment]
Closing as duplicate.
