### ISSUE TITLE
NixOS is recongnized as Unknown OS

### ISSUE THREAD

**Issue by Freed-Wu** [wakatime/wakatime-cli#885]
**Expected behavior (what should have happened)**:

**Actual behavior (what went wrong)**:

![Screenshot from 2023-05-24 00-35-27](https://github.com/wakatime/wakatime-cli/assets/32936898/6363bca9-1199-48cd-ae80-0cb4d8da0f86)

**Environment**:

- OS: linux (NixOS)
- Platform: x86_64

**Logs**:

```json
{"caller":"cmd/heartbeat/heartbeat.go:140","file":"/run/user/1000/firenvim/github.com_wakatime-wakatime-cli-issues-new_TEXTAREA-id-issue-body_2023-05-23T16-35-07-898Z.txt","func":"heartbeat.SendHeartbeats","level":"warning","message":"Too many recent heartbeats.","now":"2023-05-24T00:35:10+08:00","os/arch":"unset/unset","plugin":"vim/801 neovim-wakatime/10.0.0","time":1684859708,"version":"1.73.0"}
```

**Comment by Freed-Wu** [comment]
Maybe this is the bug of NixOS. (about `uname`?) I'll report to them <https://github.com/NixOS/nixpkgs/issues/233647>

**Comment by gandarez** [comment]
@Freed-Wu paste the output for `~/.wakatime/wakatime-cli-linux-amd64 --user-agent` (_or the correct binary for your installation_)

**Comment by Freed-Wu** [comment]
```shell
$ wakatime-cli --user-agent
wakatime/1.73.0 (linux-6.3.3-unknown) go1.20.4 Unknown/0
```

**Comment by alanhamlett** [comment]
In your log the os/arch is unknown:

`"os/arch":"unset/unset"`

We use `uname` to detect the OS so it's probably related to that Nix issue:

https://github.com/wakatime/wakatime-cli/blob/849d5c5d9dc8a5786b6a07ee0fe9a88055205b2d/pkg/system/system_linux.go#L20

**Comment by Freed-Wu** [comment]
This problem seems to disappear. Thanks!
