### ISSUE TITLE
Incorrent language shown for nu

### ISSUE THREAD

**Issue by Yakiyo** [wakatime/wakatime-cli#917]
I've been tinkering around with [nushell](https://github.com/nushell/nushell) for a bit. It seems wakatime has been detecting the language wrong

**Expected behavior (what should have happened)**:
Should detect `.nu` files as nushell (not sure wether nu is a registered language or not in wakatime). Github seems to show .nu files as nushell, so it could be either collected as a separate lang or maybe consider it just shell scripts. idk

**Actual behavior (what went wrong)**:
Its been logging it as gdscript (i assume its godot but idk)

**Environment**:

- OS: win
- Platform: 

**Logs**:
None

**Comment by gandarez** [comment]
@Yakiyo Nushell is not already implemented as a language in the Chroma library. As a workaround we can add this language in wakatime-cli.
