### ISSUE TITLE
Can not get wakatime-cli --today

### ISSUE THREAD

**Issue by holiq** [wakatime/wakatime-cli#947]
**Expected behavior (what should have happened)**: show the time today

**Actual behavior (what went wrong)**: get an error `SIGSYS: bad system call PC=0x16030 m=8 sigcode=1`

**Environment**:

- OS: Android
- Platform: arm 

**Logs**: `{"caller":"cmd/run.go:98","func":"cmd.Run","level":"debug","message":"command: today","now":"2023-10-07T14:12:34Z","os/arch":"linux/arm64","version":"v1.85.1"}`

I install wakatime with neovim on termux(android) and if i run `wakatime-cli --today` i got an error like this
So how to fix it?

![Screenshot_20231007_211516_Termux](https://github.com/wakatime/wakatime-cli/assets/30729921/9cb8229c-8acd-408b-937e-cec38e2962b3)

**Comment by gandarez** [comment]
@holiq the wakatime-cli was built excluding Android and the vim plugin needs to correctly download the new Android Build added in this [PR](https://github.com/wakatime/wakatime-cli/pull/951). @alanhamlett will take care of the vim part and let you know.

**Comment by holiq** [comment]
I don't know what's wrong, but it still not work on me (Android 13, Termux 0.118.0)
![Screenshot_20231009_105635_Termux](https://github.com/wakatime/wakatime-cli/assets/30729921/fc2e3abc-0f3d-4c81-aae6-73fdaec17897)

**Comment by alanhamlett** [comment]
Your screenshot shows you're using the Linux version. You need to download the wakatime-cli-android.

**Comment by holiq** [comment]
Oh yeah, now that work on me, thank you
