### ISSUE TITLE
wakatime plugin for perl/tcl/lua CLI REPL and gdb

### ISSUE THREAD

**Issue by Freed-Wu** [wakatime/wakatime-cli#989]
Relates issue: <https://github.com/wakatime/wakatime-cli/issues/805>

I want to share [a wakatime plugin](https://github.com/Freed-Wu/Reply-Plugin-Prompt/) which statistics time costing in perl REPL.

![screenshot](https://user-images.githubusercontent.com/32936898/226532448-84086ab6-241a-45f0-b8c1-6db8a7bb3fcf.jpg)

Similar to other wakatime plugins for REPL (bash, zsh, python, ...), I hope it can be displayed in wakatime website.

**Comment by Freed-Wu** [comment]
And there are also wakatime plugins for [tcl REPL](https://github.com/Freed-Wu/tcl-prompt) and [lua REPL](https://github.com/Freed-Wu/prompt-style.lua) :smile:

**Comment by alanhamlett** [comment]
Added all 3 to the [Terminal](https://wakatime.com/terminal) install page.

**Comment by Freed-Wu** [comment]
- there is [a wakatime plugin](https://github.com/Freed-Wu/bash-prompt) for bash REPL. I notice the original [irondoge/bash-wakatime](https://github.com/irondoge/bash-wakatime) miss a [license](https://github.com/irondoge/bash-wakatime/issues/19) and I got no response. So I write one to avoid this problem.
- A wakatime plugin to statistic the time of using gdb is [here](https://github.com/Freed-Wu/gdb-prompt). The category is `debugging`.

That's all REPLs and debuggers I used :smile:

**Comment by Freed-Wu** [comment]
A wakatime plugin to statistic the time of using gdb is [here](https://github.com/Freed-Wu/gdb-prompt).

**Comment by Freed-Wu** [comment]
![screen-2023-12-06-07-59-03](https://github.com/wakatime/wakatime-cli/assets/32936898/b6d163a6-fa6d-4b53-89f1-c9ac84fe5c90)

Hey, Can wakatime server map Reply REPL to perl REPL? Should I also change the code of the plugin?
