### ISSUE TITLE
OpenBSD Error: Prepacked binary returns `undefined symbol 'syscall'`

### ISSUE THREAD

**Issue by anoduck** [wakatime/wakatime-cli#992]
Updated my OpenBSD system and all system packages to the newest snapshot, and wakatime-cli failed to run. Error out put is as follows:

```bash
wakatime-cli:wakatime-cli: undefined symbol 'syscall'
ld.so: wakatime-cli: lazy binding failed!
```

**Environment**:

- OS: OpenBSD Current Snapshot today 12-16-23
- Platform: amd64

**Logs**:

Nothing appears to be pertanent in the logs, only that the cli failed to detect the local timezone.

**Comment by anoduck** [comment]
### To fix

I cloned the `wakatime-cli` repository from the master branch. Executed `gmake` for gnu make, and copied the resulting binary to `/usr/local/bin`. 

__Please note:__ The provided prepacked binary DID NOT work.

**Comment by gandarez** [comment]
I'm new to OpenBSD and I was trying to create a virtual machine locally on my Mac to debug this issue. Do you know how to have it running locally or any other way to run it? 

Can you also describe how did you run `gmake`?

@anoduck

**Comment by anoduck** [comment]
@gandarez Yes, sir. 

> I'm new to OpenBSD, I was trying to create a virtual machine locally on my Mac to debug this issue. Do you know how to have it running locally or any other way to run it?

What virtualization platform are you using? OpenBSD only supports open source drivers, so... you might be running into a compatibility issue. You won't be able to containerize it for use with docker or whatever... You will need to run it virtually. Qemu will work, might be slow, VirtualBox should work. Vmware is highly probable. Xen will work, but most definitely an excessive solution. 

> Can you also describe how did you run `gmake`?

I just simply ran gmake, no flags or anything. Since OpenBSD does not use the gnu variant of make, you will have to install it on your system along with golang, and bash. `doas pkg_add -U gmake go bash bash-completion git`

**Comment by anoduck** [comment]
@gandarez 
# README FIRST!!!

I just remembered, because I forgot! __This issue has nothing to do with wakatime-cli and can be closed.__ 

After performing the release upgrade, all go packages on my system had to be either reinstalled or rebuilt. Wakatime-cli was just the first package I encountered, because it runs all the time in the background.

**Comment by anoduck** [comment]
@gandarez Thank, You! Wakatime has always offered superior support, I am a big fan. Sorry about the delay closing this one out.
